### ISSUE TITLE
can intel-sgx-ssl install in a docker container？

### ISSUE THREAD

**Issue by iamzhanghaohui** [intel/intel-sgx-ssl#142] opened 2022-11-23 10:53 UTC
I try to install it in a docker container, after installing SDK and PWS， when I run `make all test`, get the error info `make sure you install the driver...`
but I can't install the driver in the container.
any ideas?

**Comment by jinghe-INTC** [comment] 2022-11-25 05:52
Can you be more specific on which step it reported the error at ? 

And have you tried SGX simulation mode with it `SGX_MODE=SIM` ?

**Comment by iamzhanghaohui** [comment] 2022-11-25 06:53
Hi, I am unable to reproduce the problem at the moment because after too many try. The issue I raised before appeared in the `make all test` step
I have solved the problem by copying it into docker after compiling it on the docker host and it works fine in the docker container.

**Comment by jinghe-INTC** [comment] 2022-11-28 02:37
Close it since it is not reproducible. Please reopen it or submit a new issue if necessary.

**Closed by jinghe-INTC** 2022-11-28 02:37 UTC
