### ISSUE TITLE
Build fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by cjpn** [intel/intel-sgx-ssl#51] opened 2020-02-02 07:28 UTC
I have just installed the Intel SGX software (driver, SDK and PSW) on Ubuntu 18.04 and I have run most of the programs in SampleCode (not RemoteAttestation or SampleCommonLoader).

I have just tried to build the SGX SSL libraries. This fails with lots of errors related to pthreads like:

In file included from enclave/tests/threadstest.c:53:0:
enclave/tests/threads.h:57:22: error: conflicting types for ‘pthread_key_t’
 typedef unsigned int pthread_key_t;
                      ^~~~~~~~~~~~~
In file included from /opt/linux-sgx/intel-sgx-ssl/Linux/sgx/../package/include/openssl/crypto.h:415:0,
                 from enclave/tests/threadstest.c:52:
/opt/linux-sgx/linux-sgx/linux/installer/bin/sgxsdk/include/tlibc/pthread.h:60:16: note: previous declaration of ‘pthread_key_t’ was here
 typedef int    pthread_key_t;

I can get the compilation to complete if I remove the compiiation of the test app from the makefile in the sgx directory. However, this seems to be storing up problems for the future.

Is there a fix for this problem, or have I done something wrong?

**Comment by andreluis034** [comment] 2020-02-03 01:20
I'm facing a similar issue utilizing the SDK and PSW from https://github.com/intel/linux-sgx/tree/9ddec08fb98c1636ed3b1a77bbc4fa3520344ede.

I believe the issue arrives because [/tlibc/pthread.h](https://github.com/intel/linux-sgx/blob/9ddec08fb98c1636ed3b1a77bbc4fa3520344ede/common/inc/tlibc/pthread.h) declares pthread_key_t, pthread_t, pthread_once_t and PTHREAD_ONCE_INIT and the same is being declared the [threads.h file](https://github.com/intel/intel-sgx-ssl/blob/master/Linux/sgx/test_app/enclave/tests/threads.h) of the test enclave. If you comment the declaration/definition of these values in the test enclave, it compiles successfully. I assume this happens because the SGX SDK got updated to include pthread but SGX-SSL did not update its code.

**Comment by cjpn** [comment] 2020-02-03 07:20
Thank you, I missed that in the flurry of error messages. I made the changes and it all completed successfully. Perhaps one of the SGX SSL team will see this and make the changes. 

I'll leave the issue open for a while so that they see it.

**Comment by g2flyer** [comment] 2020-03-16 23:57
fyi: if you use branch lin_2.9_1.1.1d and sdk 2.9, the problem is fixed. However, don't forget to install https://download.01.org/intel-sgx/sgx-linux/2.9/as.ld.objdump.gold.r1.tar.gz or you will get an error related to unknown option '-mlfence-before-indirect-branch=register' ...

**Comment by Veronicka98** [comment] 2020-04-15 08:12
hi @g2flyer, could you explain how to install this, please? I keep getting this error - '-mlfence-before-indirect-branch=register'.

**Comment by lzha101** [comment] 2020-04-15 08:22
@Veronicka98 You need to use mitigation binutils as @g2flyer mentioned.  You can download the [as.ld.objdump.gold.r1.tar.gz](https://download.01.org/intel-sgx/latest/linux-latest/as.ld.objdump.gold.r1.tar.gz), extract the tools and then refer to https://github.com/intel/linux-sgx/blob/master/README.md#prerequisites to install the tools.

> Copy the mitigation tools from external/toolset to /usr/local/bin and make sure they have execute permission:
  $ sudo cp external/toolset/{as,ld,ld.gold,objdump} /usr/local/bin
  $ which as ld ld.gold objdump

**Comment by lzha101** [comment] 2020-04-15 08:25
And suppose we can close this issue since the build failure caused by pthread type conflict has been fixed in the latest code.

**Comment by mccoysc** [comment] 2020-06-30 03:03
Assembler messages:
Fatal error: invalid -mlfence-before-ret= option: `shl'

**Comment by jinghe-INTC** [comment] 2020-06-30 08:13
> Assembler messages:
> Fatal error: invalid -mlfence-before-ret= option: `shl'

Please refer to the [reply](https://github.com/intel/intel-sgx-ssl/issues/64#issuecomment-651577069) to the other issue you opened

**Comment by jinghe-INTC** [comment] 2020-12-23 00:46
Close it since no more response from the original reporter.

**Closed by jinghe-INTC** 2020-12-23 00:46 UTC
